### ISSUE TITLE
Apropiación y validación de generalidades del sistema

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/evaluacion_mid#29]
Lectura e introducción para la apropiación de generalidades del sistema.

https://drive.google.com/drive/u/2/folders/1o5ijcCnhLDS37wL_ExgJyig7xXGV7ClC

Evaluación de proveedores desplegado en preproducción : 

https://pruebasevaluacion.portaloas.udistrital.edu.co/#/pages/dashboard

Usuario : pruebasoas2
Contraseña: pruebasoas2

**Comment by anndresfelipe29** [comment]
He revisado de la lógica del negocio de acuerdo al manual de usuario y entendiendo su funcionamiento. 
Ademas encontré una situación que me genera una duda, esto ocurrer al visualizar  la evaluación de un proveedor genera un status de error(404) y no se muestra la información general del proveedor. Esto es a causa de algo ocurrido en el api de evaluacion_mid, con la petición get de datos de contrato https://autenticacion.portaloas.udistrital.edu.co/apioas/evaluacion_mid/v1/datosContrato


 ![alt text](https://lh4.googleusercontent.com/NVsKApTIlaIzAEzqowXYyi2PSAPJAYCCP33LfZOzuLaOcyl2zjbTKsZflsoHajGSH-OfC4Sj_jEG0RdDekLmECLdxuIkYdTLk1twFzj0G7-mIPf0ZxOcdMIuSMw0L0qle9pPC529)

**Comment by Eduargonzalez** [comment]
Se programa reunión con el Ing. Juan David ( Ing. que presta servicio de soporte al sistema de Ágora) para presentarle el módulo de evaluación de proveedores y nos Guie para embeber el módulo en el sistema Ágora propiamente. En primer lugar para que cada proveedor pueda ver su evaluación. y en segundo lugar para que el supervisor pueda ver la evaluación de los proveedores para previamente escoger el mejor proponente.  meet.google.com/rzp-iqgm-tjb  @ddguerra90  @FrederickUdis

**Comment by FrederickUdis** [comment]
se realizo pruebas de la api evaluacion_cliente en la rama master y se presento el mismo problema 404 al momento de pedir una petición a la api 
![image](https://user-images.githubusercontent.com/30853509/97021579-9f3e7100-1518-11eb-8d87-404bdb8ab4a3.png)
se procedió a hacer pruebas con postman y no se logro conectar con la api.
posiblemente el error es de la api.

**Comment by ddguerra90** [comment]
Para entender un poco mejor lo que se realizo se recomienda revisar la fase anterior del desarrollo de Agora. En el siguiente enlace esta el proyecto y las tarjetas relacionadas al sistema Agora.

https://github.com/orgs/udistrital/projects/10

**Comment by ddguerra90** [comment]
Se solicitan las variables de entorno de evaluacion_mid a soporte para correr el api en local y poder rastrear el error anteriormente mencionado:

ADMIN_AMAZON_API_URL http://pruebasapi.intranetoas.udistrital.edu.co:8104/
ADMIN_AMAZON_JBPM_URL http://jbpm.udistritaloas.edu.co:8280/services/
AWS_DEFAULT_REGION us-east-1
EVALUACION_CRUD_URL http://pruebasapi.intranetoas.udistrital.edu.co:8506/
PARAMETER_STORE preprod

**Comment by FrederickUdis** [comment]
El dia de hoy se realizaron las pruebas para encontrar los datos traídos por el api y se encontró que en controllers/datoscontrato.go la función
![image](https://user-images.githubusercontent.com/30853509/98320351-bec1a900-1fb0-11eb-96db-53b162f52d35.png)
trae los datos numéricos del contrato en notación científica, como se pude ver en la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/98320544-2c6dd500-1fb1-11eb-8236-738903c47da9.png)

**Comment by FrederickUdis** [comment]
se soluciono el error de los datos del supervisor  mejorando la petición a  administrativa_amazon_api_url 
![image](https://user-images.githubusercontent.com/30853509/98597003-4f94cf00-22a6-11eb-8cc0-e65d86e16afc.png)
además se convirtió el valor  del documento del supervisor como lo muestra la siguiente imagen.
![image](https://user-images.githubusercontent.com/30853509/98597113-7a7f2300-22a6-11eb-82f7-8c32c149669b.png)
