### ISSUE TITLE
Pruebas Unitarias y refactor api crud

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/evaluacion_mid#35]
Hacer refactor del api evaluacion_crud segun los lineamientos establecidos por la OAS y las pruebas unitarias de ser necesarias.

https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/control_error_json_crud.md
https://github.com/udistrital/lineamientos_oas/blob/master/pruebas_unitarias_api_beego/crud_test.md

**Comment by ddguerra90** [comment]
Se adjunta issue donde se menciona el modelo de la base de datos y un modelo de la base de datos
https://github.com/udistrital/evaluacion_cliente/issues/11

![image](https://user-images.githubusercontent.com/31446845/108733030-19e5c000-74fc-11eb-9df1-273f252500b1.png)

**Comment by diagutierrezro** [comment]
Se realiza el refactor del crud según los lineamientos de la OAS que se encuentran en https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/control_error_json_crud.md donde se ajusta le estructura de la respuesta que devuelve el crud bien sea por una petición correcta o con algún error.

**Comment by diagutierrezro** [comment]
Al realizar una petición al api este responde de la manera esperada con la estructura del refactor
![image](https://user-images.githubusercontent.com/38676533/109322756-aa840f00-7820-11eb-8bcb-a86b13d2de58.png)
