### ISSUE TITLE
Refactor api mid

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/evaluacion_mid#39]
Hacer refactor del api evaluacion_mid segun los lineamientos establecidos por la OAS.

https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/control_error_json_mid.md

**Comment by diagutierrezro** [comment]
1. Primero se ajustan las respuestas que recibe por parte del crud de evaluación ya que a este también se le realizó refactor: https://github.com/udistrital/evaluacion_mid/issues/35 
2. Se realiza el refactor del api mid de evaluación de la siguiente manera:
- En los controladores ya no se manejará logica, solo un control de que los datos ingresados son validos, un defer en caso de llegar un panic y controlar el error o en caso de que la petición sea correcta se retorna con la estructura requerida.
![image](https://user-images.githubusercontent.com/38676533/109319716-2bd9a280-781d-11eb-8d65-a29438b45de7.png)
- La logica que se quitó de losa controladores se pasaron a otros archivos dentro de una carpeta helpers
![image](https://user-images.githubusercontent.com/38676533/109319824-4e6bbb80-781d-11eb-82c8-ddccaa183386.png)
- Tanto en los helpers como en los modelos se realiza un control de errores con posibles fallos que puedan ocurrir en la api bien sea al realizar peticiones a sistemas externos o en la logica del api
![image](https://user-images.githubusercontent.com/38676533/109320046-925ec080-781d-11eb-8844-3b73d31dc673.png)

**Comment by diagutierrezro** [comment]
Se puede observar que al realizar una petición al api este responde de manera correcta
![image](https://user-images.githubusercontent.com/38676533/109322088-dce13c80-781f-11eb-8f0e-c6805d40e16f.png)
